### ISSUE TITLE
zmena domeny

### ISSUE THREAD

**Issue by stepjan** [Sumbera/iKatastr.cz#1]
Dobrý den,

prosím o změnu domény pro získávání mapových podkladů od Seznam.cz z http://m1.mapserver.mapy.cz  na https://mapserver.mapy.cz (tedy přejít na https + zrušit)

Děkuji
Jan Štěpán
Seznam.cz

**Comment by Sumbera** [comment]
Dobry den, 
OK, udelam to pri nejblizsi prilezitosti, diky za upozorneni !

Stanislav Sumbera

**Comment by Sumbera** [comment]
opraveno, diky za info.
