### ISSUE TITLE
info z katastru nemovitostí - vlastníci

### ISSUE THREAD

**Issue by henkye** [Sumbera/iKatastr.cz#15]
Zdravím. V malém náhledovém okénku 'info z katastru nemovitostí' mi chybí výpis vlastníků. Je to pro mě hlavní informace a kvůli ní musím otevírat a přepínat se na nové okno. Mnohem lepší by bylo zobrazovat rovnou.

**Comment by Sumbera** [comment]
Dobry den, to bohuzel nejde, resp. by to znamenalo porusovani podminek pouzivani sluzeb CUZK, ktere zase musi ctit ochranu osobnich udaju a jine nalezitosti. Vlastnici se zobrazuji pouze v interaktivnim oknu.  Jakmile by to bylo k dispozici jako strukturovany udaj v nejake oficialni sluzbe, rad to tam pripojim, ale necekam, ze se to kvuli GDPR stane.

**Comment by henkye** [comment]
Tušil jsem to, ale člověk nikdy neví. Díky za info a podporu.
