### ISSUE TITLE
v mobilním Chrome nefunguje vrstva katastrálních map

### ISSUE THREAD

**Issue by lupynos** [Sumbera/iKatastr.cz#19]
v mobilním Chrome nefunguje vrstva katastrálních map (android 10, Chrome), podkladové mapy fungují

workaround: zapnout zobrazení stránky jako pro počítač a pak zase vypnout

**Comment by Sumbera** [comment]
diky, muzete zkusit jestli nefunguji jakekoli vrstvy ? (napr povodne, bremena ) , neni to nejaky problem leafletu ? vice info a chovani v teto konfiguraci pomuze ...  take konkretni verze chromu na mobilu apod...

**Comment by lupynos** [comment]
Zdravím, týká se to všech vrstev (katastr, povodně, atd.), vypadá to na nějaký nešvar leafletu.
Po použití workaroundu, jak jsem psal výše, to začne chodit.

Chrome (Android)  84.0.4147.125
Android 10, SM-G970F

edit: na Edge Android 45.06.2.5042 to jede ok, tak by to mohlo být jen verzí jádra chromium

**Comment by Sumbera** [comment]
@lupynos dokazu to navodit na Androidu 9 ... pokud udelate jen refresh melo by se to take zobrazit... ale  v incognito modu vrstvy jedou vzdy. To je hodne divny.... dival jsem se znovu na to, problem je zrejme nekde v casovani nacitani vrstev. Jednoducha vrstva funguje. muzete prosim vyzkouset na Vasi konfiguraci  tuto adresu: https://spatialin.com/2020/test/testWMS.html - tam by se mely vrstvy zobrazovat bez problemu

**Comment by Sumbera** [comment]
opraveno ! :)  trochu to dalo prace...  diky za upozorneni  !
