### ISSUE TITLE
Nefunkční odkaz na katastrální území

### ISSUE THREAD

**Issue by rsafcz** [Sumbera/iKatastr.cz#2]
Při kliknutí na název katastrálního území (v rámečku vlevo dole) se na webu CUZK objeví chyba 404
https://www.cuzk.cz/Dokument.aspx?AKCE=META:SESTAVA:MDR002_XSLT:WEBCUZK_ID:718211

**Comment by Sumbera** [comment]
dekuji, vim o tom, nefungujou ani odkazy na CUZK tak snad ten vypadek opravi... pokud byste nasel nove odkazy prvni (nebo zjistite ze uz to funguje), prosim uverejnete je sem at to muzu opravit nebo ostatni budou vedet ze uz to funguje....dekuji

https://www.cuzk.cz/Katastr-nemovitosti/Informace-o-katastralnich-uzemich.aspx

**Comment by Sumbera** [comment]
odkazy opet funguji
