### ISSUE TITLE
Nelze vyhledávat?

### ISSUE THREAD

**Issue by ackvf** [Sumbera/iKatastr.cz#20]
Překvapilo mne, že na stránce chybí vyhledávání, které jsem nakonec našel s atributem `visibility: hidden`.
Nicméně ani po zobrazení elementu vyhledávání nefunguje - asi proto bylo skryté :)
Otázka tedy zní, jak mohu v mapě něco vyhledat?
![image](https://user-images.githubusercontent.com/2313018/101164077-e437e600-3634-11eb-94eb-ea12add6d043.png)

**Comment by Sumbera** [comment]
je skryte protoze se musi nejdrive nacist asynchronne javascript z mapy.cz ktery vyhledavani zajistuje - takze se zrejme skript nenacetl - chtelo by to videt konzoli. Ale dekuji za info...

**Comment by ackvf** [comment]
Aha, tak v tom případě byl určitě problém s firemní VPN. Na jiném PC ve stejné síti to už funguje v pořádku (tedy již bez VPN).
Mohl bych tak alespoň navrhnout, aby se tlačítko zobrazilo i v případě chyby, ale bylo buď zamčené nebo např. zobrazilo chybu při přejetí myší?
Působilo dost zmateně, že na stránce nebylo vyhledávání vidět a že nebylo dostupné ani skrze nějaké menu, atp. a trvalo mi dobrých 20 minut lámání si hlavy a hledání na internetu "jak vyhledávat na ikatastr", než jsem narazil na #12, podle kterého jsem pochopil, že za normálních okolností by měl i nezkušený Tonda vyhledávání najít.

Chybějící prvky v UI obecně působí zmateně. Lepší je právě zobrazit celé UI, ale předat uživateli zprávu, že je něco špatně. Čili přeferovat explicitní selhání, než implicitní fallback/degradaci.

**Comment by Sumbera** [comment]
diky za dobry  podnet, popremyslim o tom.
