### ISSUE TITLE
náhled panorama mapy.cz

### ISSUE THREAD

**Issue by Zick01** [Sumbera/iKatastr.cz#21]
zdravím, nejspíš po nějaké aktualizaci nastala situace, že při vybrání "objektu" se hned u něj nezobrazí šipečka s možností prokliku na panoramu mapy.cz. Dříve to bylo defaultně... nyní musím vybrat jinou parcelu, kde se pak šipička ukáže a pak lze panoramu zobrazit.
![image](https://user-images.githubusercontent.com/79198044/108191909-f98cbe80-7113-11eb-928e-6967e91009c6.png)

**Comment by Sumbera** [comment]
prosim o prohlizec, OS popr dalsi podrobnosti. Kazdopadne diky za info !

**Comment by Zick01** [comment]
macOS Catalina 10.15.7 (19H524), Google Chrome Verze 88.0.4324.150 (Oficiální sestavení) (x86_64) nefunguje to při přesměrování z aplikace nemokalk.cz. Pokud si kliknu v prohlížeči na jakoukoli parcelu, šipička tam vyjede. Nevyjede tedy pravděpodobně při přechodu z webu nemokalk.... zobrazí se pouze náhladové info z katastru, obrys parcely, ale chybí tam šipečka na náhled panoramy

**Comment by Sumbera** [comment]
aha uz to vidim, mapy.cz / panorama se nacitaji az pozdeji, takze API panoramy neni k dispozici, pokud ale udelate refresh stranky, melo by se objevit. Je ot chyba, podivam se na to..

**Comment by Sumbera** [comment]
opraveno, panorama sipka se objevi jakmile se nactou patricne komponenty z API MAPY.cz. Diky za upozorneni na chybu !
