### ISSUE TITLE
dmr/hillshade vrstvy pod topo mapou

### ISSUE THREAD

**Issue by petrpajdla** [Sumbera/iKatastr.cz#3]
Zdravím,
poměrně často využívám webaplikaci, především ZM, a současné podložení topomapy stínovaným reliéfem mi nepřipadá úplně šťastné, čitelnost mapy je o něco horší. Bylo by možné přidat hillshade jako volitelnou vrstvu, popřípadě vlastní možnost úpravy průhlednosti jednotlivých vrstev?
Jinak je aplikace velmi praktická a jednoduchá, což oceňuji.
Díky,
Petr Pajdla
ARUB AV ČR

**Comment by Sumbera** [comment]
chapu, dost jsem s tim bojoval, aby to vypadalo aspon nejak prijatelne, vadi mi i to ze se nacitaji jako by 2 vrstvy, zkusim to predelat...asi to nema zas takovy vyznam ten stinovany relief ?

**Comment by Sumbera** [comment]
hillshade je prozatim vypnuty

**Comment by petrpajdla** [comment]
Super, myslím, že takhle je to přehlednější, ale tak těžko říct, co by o tom soudili další uživatelé. On ten hillshade moc informací nepřidá, když v topomapě jsou stejně vrstevnice, jako může to vypadat hezky, ale záleží na účelu, k čemu to kdo používá asi.
Ještě jednou díky, kdybych měl nějaké další připomínky ozvu se.
