### ISSUE TITLE
Čísla parcel jiná vrstva + Hranice parcel

### ISSUE THREAD

**Issue by mullerpetr76** [Sumbera/iKatastr.cz#31]
Hezký den,
změny v posledních týdnech nejsou k lepšímu.
iKatastr je o parcelách a jejich číslu.
Mít to jako vrstvu, kterou si musím zapnout je nelogické.
Odkazy, které jsem si udělal v Excelu, které, jak jistě víte, je netriviální změnit, mi nyní nefungují.
Po kliknutí v Excelu musím ručně přidat vrstvu číslo parcel.
Ale na některých místěch mapy se stejně číslo nezobrazí.
A na některých místěch mapy dokonce chybí parcely!
Viz:
https://www.ikatastr.cz/#kde=50.12009,14.2998,19&mapa=zakladni&vrstvy=parcelybudovy,cislaparcel

![obrazek](https://user-images.githubusercontent.com/66279944/144557526-cf3b85be-a1a1-41d8-9e23-a6ccb5ca8716.png)

**Comment by Sumbera** [comment]
dobry den, to vypada ze se nenacetla vubec vrstva, problem bud v siti nebo na strane CUZK, ktere obcas muze provadet udrzbu a vrstvy (data) nejsou plne dostupna, resp pouze cache. Zkuste to pozdeji, nebo kliknout primo na pozadovanou parcelu. Nemohu s tim nic delat. Kousek dal to opet funguje : https://www.ikatastr.cz/#kde=50.12565,14.27434,19&mapa=zakladni&vrstvy=parcelybudovy,cislaparcel,cislabudov&info=50.1185,14.29767 tedy predpokladam ze na cuzk probiha udrzba - mozna se obratte primo na ne.
Pokud se podivam do VDP (Marushka) vypada to uplne stejne:
![image](https://user-images.githubusercontent.com/598862/144567898-b943f76b-209f-4203-8911-59944b703f8b.png)

**Comment by mullerpetr76** [comment]
Nejde o náhodu. Těch míst je několik a někde se zobrazuje a někde ne. 
Šlo navíc o dva problémy:
1) čísla nutné zapnout
Link:
https://www.ikatastr.cz/#kde=50.11928,14.39474,19&mapa=satelitni&vrstvy=parcelybudovy
dříve zobrazoval čísla parcel, dnes je nutné přidat do URL ",cislaparcel"
Jde o novou funkcionalitu?

2) čísla jen někde
varianta a - nejsou čísla:
https://www.ikatastr.cz/#kde=50.11928,14.39474,19&mapa=satelitni&vrstvy=parcelybudovy,cislaparcel
![image](https://user-images.githubusercontent.com/66279944/144589801-2fa66aeb-dbfa-4470-8a5c-2587d7c7b1c7.png)

varianta b - jsou čísla
https://www.ikatastr.cz/#kde=50.19804714,14.23451371,19&mapa=satelitni&vrstvy=parcelybudovy,cislaparcel
![image](https://user-images.githubusercontent.com/66279944/144590074-006a4581-2849-4400-8868-fe2ecfd92d4a.png)

3) obrysy parcel
varianta a - jsou obrysy
na většině míst jsou obrysy

varianta b - chybí obrysy
https://www.ikatastr.cz/#kde=50.11961,14.30085,19&mapa=zakladni&vrstvy=parcelybudovy,cislaparcel
![image](https://user-images.githubusercontent.com/66279944/144590383-d7dfb4fa-d3c5-43e5-bff1-59271e261fb1.png)

ANO, jde zjevně o chybu katastru:
![image](https://user-images.githubusercontent.com/66279944/144590569-f198ef30-19e8-48ec-a328-bd60a034e460.png)


Prosím tedy reakci na bod 1 a 2

**Comment by mullerpetr76** [comment]
@Sumbera prosím o reakci na bod 1 a 2. Děkuji! :)

**Comment by Sumbera** [comment]
#2 Bylo by dobre kontaktovat primo CUZK, myslim si, ze se jedna o spatne vygenerovana data (dlazdice) , mozna o tom vubec nevi, muze jit o chybu v jejich rendrovacim softwaru, nebo doslo k nejake vyjimce behem generovani a nikdo si toho (v tom objemu) zrejme nevsiml. Budu rad, pokud se toho ujmete - pomuzete i ostatnim :)

#1 ano cisla je nutne zapnout, ale ikatastr si to pamatuje v cookies, takze pokud to neprepisete necim jinym a napisete pouze  ikatastr.cz tak se vam obnovi posledni nastaveni, ale vidim tam jednu chybku, pokud napisu do url https://ikatastr.cz/#kde=49.23058,17.31415,19 (bez vrstev) tak se puvodni vrstvy neobnovi a to je zrejme problem na ktery upozornujete, dekuji.

**Comment by mullerpetr76** [comment]
Hezký den,
>> pokud napisu do ... (bez vrstev) tak se puvodni vrstvy neobnovi
Ne, na to neupozorňuji.
Problém 2a:
![image](https://user-images.githubusercontent.com/66279944/144643776-1eba3a13-e0ce-48e9-867a-881c385fd33e.png)
je v tom, že nejsou vidět čísla, jen modré body. 
Už to vidíte?

**Comment by Sumbera** [comment]
ano, o tom jsem psal - nahlaste to na CUZK, pokud byste zjistil rozdil mezi iKatastr.cz a VDP (Maruska) na stejnem uzemi a se stejnymi vrstvami prosim sdelte to. Me se na Podbabske cisla zobrazuji: https://ikatastr.cz/#kde=50.12004,14.39298,20&mapa=zakladni&vrstvy=parcelybudovy,cislaparcel,cislabudov


zkuste udelat refresh stranky, nebo jiny prohlizec, nebo anonymni prohlizeni pro zneplatneni kese. Ale hlavni problem je v tom, ze se musite zrejme problizit vice (zoom in) Vypada to, ze jedete na mobilnim zarizeni ?

**Comment by mullerpetr76** [comment]
@Sumbera už to asi obojí opravili :) díky a omlouvám se za "křívé obvinění" :)
