### ISSUE TITLE
Vyhledávání ukáže ulici v jiném městě

### ISSUE THREAD

**Issue by myneur** [Sumbera/iKatastr.cz#39]
<img width="912" alt="Screenshot 2023-12-11 at 10 02 54" src="https://github.com/Sumbera/iKatastr.cz/assets/105628/9fc27cc4-7095-4c83-bf8c-1d5d50ae19d0">

Při vyhledávání ulice "Nádražní, Žirovnice" našeptávač korektně nabídne tuto ulici, ale při kliknutí na položku našeptávače to v mapě skočí na stejnojmennou ulici v Praze.

**Comment by martinsuchan** [comment]
Stejný problém, když dám hledat "Jana Roháče z Dubé Louny", tak mi to našeptá správně, ale klikem se dostanu do Čáslavi
![image](https://github.com/Sumbera/iKatastr.cz/assets/3041397/d528f2b8-aee5-4245-9c46-9313f1f64b67)

**Comment by vizustom** [comment]
Našeptávání funguje dobře, ale ať se klikne na kteroukoliv našeptanou variantu, ikatastr vždy vybere tu první našeptanou variantu.

**Comment by Sumbera** [comment]
diky za podrobny navod jak to navodit - zkusil jsem to a opravdu to funguje jak pisete, zkusim se na to v nejblizsich dnech podivat...

**Comment by Sumbera** [comment]
melo by to byt opraveno, vyzkousejte + refresh stranky / vypnout cache, nebo private window apod.

**Comment by myneur** [comment]
Funguje, díky
