### ISSUE TITLE
měření vzdáleností a plochy?

### ISSUE THREAD

**Issue by Markde1** [Sumbera/iKatastr.cz#4]
Je někde dostupná funkce měření vzdáleností a plochy? Jako to bylo v minulé verzi? Je možné to prosím doplnit? děkuji Klimeš

**Comment by Sumbera** [comment]
Ano...pracuje se na tom,  prozatim pokdu mereni potrebujete, pouzivejte prosim starsi verzi: https://ikatastr.cz/ikatastr.htm

**Comment by Sumbera** [comment]
mereni je doplneno v desktop verzi
