### ISSUE TITLE
Ikona Vyhledávání

### ISSUE THREAD

**Issue by Gradace** [Sumbera/iKatastr.cz#40]
Kam se poděla v https://www.ikatastr.cz/ v nabídce ikona vyhledávání adresy? Díky za odpověď.

**Comment by Sumbera** [comment]
Dekuji za upozorneni, Mapy.cz ukoncily zrejme sve puvodni API, vyhledavani bude muset byt nahrazeno/prepsano. V nejblizsich dnech se na to podivam jak to vyresit. Napady a pomoc vitana.

**Comment by Sumbera** [comment]
chyba byla  odstranena, dekuji za vcasne upozorneni. Privedlo me to na zjisteni, ze soucasne  vyhledavani (komponenta  z  Mapy.cz) bude zruseno a  nahrazeno verzi zde : https://developer.mapy.cz/js-api/ukonceni-podpory-js-sdk/
