### ISSUE TITLE
Nepodporovaná verze knihovny JS SDK

### ISSUE THREAD

**Issue by martinsuchan** [Sumbera/iKatastr.cz#42]
Vyhledávání ukazuje chybu o nepodporované verzi knihovny, viz:
https://developer.mapy.cz/js-api/ukonceni-podpory-js-sdk/
![image](https://github.com/user-attachments/assets/5f534279-5186-47a5-adc6-b34745be060d)

**Comment by Sumbera** [comment]
vyhledavani je ode dneska  nove, pokud byste zaznamenal problemy dejte prosim vedet.
