### ISSUE TITLE
Vyhledávání podle GPS

### ISSUE THREAD

**Issue by Lada139** [Sumbera/iKatastr.cz#43]
Můžu prosím dotaz?
Proč od včera nejde vyhledávat místo podle GPS?
Díky Laďa

**Comment by Sumbera** [comment]
mel by to jit normalne, zkuste resetovat cache, spustit private mode, apod. GPS funkcionalita by mela fungovat uplne stejne jak pred tim, me to funguje na iOS i Androidu.

**Comment by Sumbera** [comment]
zkuste tuto URL adresu : https://ikatastr.cz/index3.htm, ktera je jen testovaci a nebude v dalsich dnech zrejme k dispozici, ale mela by vse nacist znovu.
