### ISSUE TITLE
Nevyskakují okna

### ISSUE THREAD

**Issue by milhause88** [Sumbera/iKatastr.cz#44]
Zdravím od včerejšího dne mi nevyskakují okna pro zadání adresy a vrstvy. Lišta po kliknutí nereaguje.
V microsoft edge to funguje.

Díky Milan

**Comment by Sumbera** [comment]
to je problem s cache, zkuste CTRL-R pro obnovu stranky, zkuste anonymni okno, pokud nic nezabere, zkuste nouzove : ikatastr.cz/index3.htm - ale tato stranka brzy prestane fungovat  a bude jen index.htm .
Dejte mi vedet co pomohlo… a zda-li to uz u vas funguje. Updatoval jsem index.htm aby si bral nove pojemnovane soubory a nekriizlo se to s kesi.  Muzete take zkusit prave tlacitko mysi - reload:

<img width="249" alt="image" src="https://github.com/user-attachments/assets/1eb1d81d-411a-4388-b1cd-744b4d748383">
