### ISSUE TITLE
Vyhledávání dle souřadnic

### ISSUE THREAD

**Issue by Alice-Pajerova** [Sumbera/iKatastr.cz#45]
Dobrý den,
zřejmě po přechodu na REST API nelze v aplikaci vyhledávat dle souřadnic. Do 1. 10. 2024 jsme vyhledávali dle souřadnic WGS 84 vyhledávali bez problémů. Nelze ani podle souřadnic S-JTSK.
Bylo by možné tuto možnost vyhledávání obnovit?
Děkuji 
Pajerová

**Comment by Sumbera** [comment]
Dobry den,
to jsem ani nevedel ze to jde :) jak souradnice vyhledavate, prosim o priklad abych to mohl zaradit do noveho vyhledavani.
Zatim muzete vyuzit starou verzi, ktera je archivovana  zde: https://spatialin.com/2024/iKatastr

**Comment by Alice-Pajerova** [comment]
> Dobry den, to jsem ani nevedel ze to jde :) jak souradnice vyhledavate, prosim o priklad abych to mohl zaradit do noveho vyhledavani. Zatim muzete vyuzit starou verzi, ktera je archivovana zde: https://spatialin.com/2024/iKatastr

Používám souřadnice z jiných map, lze např. i ze seznam mapy. Zkopíruji souřadnice a vložím do políčka vyhledávání. 
Děkuji, odkaz vyzkouším.

**Comment by Alice-Pajerova** [comment]
Upřesnění a screenshoty:
stará verze při vložení souřadnic (jedno jestli v souřadnicovém systému S-JTSK nebo WGS 84 (Výstřižek1)) místo našla (Výstřižek2). Nová souřadnice červeně podtrhne a nic nenajde (Výstřižek3)

Dosud jsme s kolegy byli s aplikací velice spokojeni a kdyby se Vám podařilo vyhledávání podle souřadnic obnovit, byli bychom Vám nekonečně vděční.

Děkuji za ochotu.
Výstřižek1:
![Výstřižek1](https://github.com/user-attachments/assets/4b06aefe-1b7a-49a8-88bf-c2f7dfde4953)
Výstřižek2:
![Výstřižek2](https://github.com/user-attachments/assets/64a21382-2847-4500-9f64-597d240d748b)
Výstřižek3:
![Výstřižek3](https://github.com/user-attachments/assets/e14bdbf1-9b31-481e-a0d6-9449fc31ef76)

**Comment by uzivatelZJ** [comment]
Dobrý den, také se velmi přimlouvám za obnovení této funkce.
Děkuji!

**Comment by Sumbera** [comment]
Funkci jsem pridal, neobjevi se zadny naseptavac, ale na Enter, nebo kliknutim na ikonu lupy se pozice vyhleda.

**Comment by uzivatelZJ** [comment]
Skvělý, moc děkuji!
Zdeněk Jahn

po 28. 10. 2024 v 21:23 odesílatel ∫ ∪ ∧∴ ∋ ∈ ⊇ ∧ ***@***.***>
napsal:

**Comment by Alice-Pajerova** [comment]
Mnohokrát děkujeme za vstřícný přístup a rychlost.
Pajerová & spol. :-)

**Comment by Sumbera** [comment]
rado se stalo !
