### ISSUE TITLE
Opravil byste prosim hledani adresy v nativni ios app?

### ISSUE THREAD

**Issue by joscees** [Sumbera/iKatastr.cz#7]
Dekuji predem.

**Comment by Sumbera** [comment]
pouzijte prosim webovou aplikaci.

**Comment by joscees** [comment]
No to prave nechci, stale refreshovat na mobilnich datech, ta aplikace uz je mrtva?

**Comment by Sumbera** [comment]
Nova verze webove mobilni aplikace je napsana tak, ze ji nemusite 'stale refreshovat' , je velmi stihla, a v konecnem dusledku by Vam nemela vzit vice dat nez nativni aplikace. Vice o tom na blogu zde: https://blog.sumbera.com/2018/09/07/ikatastr-cz-pro-mobilni-web/ . Takze ji smele vyzkousejte a pokud zjistite konkretni cisla spotreby mobilnich dat, urcite je nevahejte sem napsat. 

Tesi me sice, ze pouzivate nativni aplikaci, ale cas pokrocil, mobilni zarizeni jsou vykonejsi, mobilni data dostupnejsi, 3G/LTE pokryti .  Na jednoduche zobrazeni mapy a dotazu Vam opravdu staci dnes uz jen  web. Tedy zkuste, prosim,  tomu webu dat sanci, pokud mate konkretni vytky vuci webove aplikaci na mobilu, velmi rad je vyslechnu a zapracuju na jejich odstraneni/vylepseni.

Byl bych rad, kdyby se uzivatele nativni aplikace dokazali presunout na web, ktery je ted prioritou a je ze vsech platforem nejpopularnejsi,  viz statistika zde: https://blog.sumbera.com/2016/04/06/pc-web-vs-mobile-app-usage/

**Comment by Sumbera** [comment]
Podarilo se mi vzdalene prekonfigurovat vyhledavani na iKatastr2 na iOS. Vyzkousejte. V policku vyhledat byste mel videt "Vyhledat geograficky nazev"

**Comment by joscees** [comment]
Supeer...

Skoda ake ze nova verze rovnou haze na webovou stranku :-(

Bylo by mozne prosim 
- nejak zachytit URL? Napriklad dlouhym podrzenim treba 10s by se url pred zakodovanim zkopirovalo do schranky :)
- otevirat plny detail? Jak to blokuji, pres referer nebo pres cookies?

Diky.

Ps metry jsou dobra vychytavka, jak to funguje? Nejaky orientacni vypocet na zaklade orientacnich lomovych bodu? Na nekterych kratsich spojich se vzdalenost neobjevi ani pri max. zoomu :-(
